name: Terms Of Service

dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 5.0.1

solidity:
  import_remapping:
    - "@openzeppelin=OpenZeppelin/v5.0.1"

plugins:
  - name: solidity
    version: 0.7.0
