name: ape-playground

ethereum:
  local:
    # Tracing features are required.
    default_provider: geth

plugins:
  - name: vyper
    version: git+https://github.com/antazoey/ape-vyper.git@test/cov

test:
  coverage:
    exclude:
      - method_name: "DEBUG_*"
      - contract_name: "Debug"
      - contract_name: Ignore*
        method_name: FOOBAR_*

    reports:
      terminal: True
      html: True
      xml: True
