on: ["push", "pull_request"]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: Test

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: antazoey/github-action@feat/much-upgrade
      with:
        python-version: "3.10"
        ape-remote-git-version: "git+https://github.com/aladagemre/django-notification.git@2927346f4c513a217ac8ad076e494dd1adbf70e1"

    - run: ape test --coverage

    - uses: codecov/codecov-action@v3
      name: Upload to CodeCov
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: .build/coverage.xml
        flags: unittests # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
