on: ["push", "pull_request"]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: Test

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: antazoey/github-action@feat/much-upgrade
      with:
        python-version: "3.10"
        ape-version-pin: "git+https://github.com/antazoey/ape.git@feat/cv#egg=eth-ape"
        ape-plugins-list: vyper@git+https://github.com/antazoey/ape-vyper.git@test/cov

    - run: ape test --coverage

    - uses: codecov/codecov-action@v3
      name: Upload to CodeCov
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: .build/coverage.xml
        flags: unittests # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
